name: Main CI Jobs

on: [push, pull_request]

jobs:
  uv_setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Check uv version
        run: |
          uv --version

      - name: Setup venv and python packages
        run: |
          uv venv -p ${{ matrix.python-version }}
          uv pip install numpy

      - name: Run python script
        run: |
          uv run test.py
