name: Main CI Jobs

on: [push, pull_request]

jobs:
  uv_setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Check uv version
        run: |
          uv --version

      - name: Activate python venv
        run: |
          uv venv
